---
title: "Onboarding"
---

# Onboarding for new team members on NCEAS Data Science Support Team

This repository hosts onboarding materials for new team members on the NCEAS Data Science support team.

Listed below are a mix of references and tutorials on concepts we aim to promote to researchers we support, as well as tools and workflows we use in our team.  The goal is to give context about open and reproducible science principles NCEAS is promoting to the scientific community.  you will also find information on getting access to the tools you will need and some general information about working at NCEAS.

---

### Introductory Reading Materials

#### Background information

* Hampton et al 2015. ["The Tao of open science for ecology"](https://doi.org/10.1890/ES14-00402.1)

* Borer et al 2009. ["Effective Data Management"](https://doi.org/10.1890/0012-9623-90.2.205)

* Fegraus et al 2005. ["Maximizing the Value of Ecological Data with Structured Metadata:"](https://doi.org/10.1890/0012-9623%282005%2986[158:MTVOED]2.0.CO;2)

* Heidborn 2008. ["Shedding Light on the Dark Data in the Long Tail of Science"](http://doi.org/10.1353/lib.0.0036)

---

### Programs & Resources

#### 1. GitHub

We rely heavily on GitHub for collaboration, and there are a few things you must do to get set up:

##### a. Get added to the NCEAS GitbHub Enterprise account:

We use a GitHub Enterprise account to keep track of projects and tasks for the Scientific Computing Support of SNAPP working groups.  To be added to the account you must create an NCEAS account.

Follow the directions outlined [here](https://docs.google.com/document/d/1eoR1oDrCrczgbYHPZU_1szB_2fhzu7EUHnh5nFI3eSg/edit) and send your username to Julien Brun (not the email outlined in the google doc).  After you have been added, you will be able to access the [lter-wg-scicomp](https://github.nceas.ucsb.edu/LTER/lter-wg-scicomp) GitHub. We will use this repo to track tasks among our team.

##### b. Get added to the LTER GitHub Organization

Register (if you have not already) for a personal GitHub account and send your username to Julien to be added to the [LTER GitHub](https://github.com/LTER).  This GitHub has the working groups repositories that you will be directly working with.

##### c. Complete the NCEAS GitHub tutorial [here](https://nceas.github.io/training-git-intro/getting-started-with-git-rstudio.html)

This tutorial will help you with getting starting with git and GitHub using RStudio

#### 2. Slack

We use Slack to communicate with one another throughout the day. To be added to the NCEAS Slack group, register [here](https://slack.nceas.ucsb.edu/).  If you already have a slack account, be sure to use the email address you used to register.

Find and join our #scicomp channel by clicking the plus sign next to the Channels section.  Feel free to join any other channels that you might find interesting! Popular channels include hackeyhour, science, and social.

Finally, complete this short tutorial on using Slack: https://pages.github.nceas.ucsb.edu/NCEAS/help/chat_room_setup.html

#### 3. Aurora Server

We use the Aurora server (located at aurora.nceas.ucsb.edu) when working with RStudio or JupyterHub. Send an email to help@nceas.ucsb.edu requesting an account mentioning you are working with Julien. Thomas Hetmank or Nick Outin will contact you with directions for setting up an account.

### Recurring NCEAS Meetings

There are a number of recurring meetings that you are encouraged to attend.  At your hiring, you should recieve an invitation to the NCEAS Google Calendar which has links to all the meeting information.  These include Coffee Klatch (a coffee social), Hacky Hours, and the Early Career Researcher Community Forum.

---

### Data Science background and tutorials

For good background information on the tools that we use, read through and practice examples of the following chapters from a training we did for postdoc early 2020: https://science-for-nature-and-people.github.io/2020-data-collab-workshop/2020-02-snapp/index.html

Chapters [3](https://science-for-nature-and-people.github.io/2020-data-collab-workshop/2020-02-snapp/working-on-a-remote-machine.html), [5](https://science-for-nature-and-people.github.io/2020-data-collab-workshop/2020-02-snapp/introduction-to-r-and-rmarkdown.html), [8](https://science-for-nature-and-people.github.io/2020-data-collab-workshop/2020-02-snapp/linux-and-the-command-line.html) are a good background about the tools we use.

Chapters [9](https://science-for-nature-and-people.github.io/2020-data-collab-workshop/2020-02-snapp/data-modeling-tidy-data.html), [10](https://science-for-nature-and-people.github.io/2020-data-collab-workshop/2020-02-snapp/data-cleaning-and-manipulation.html) are a good introduction to data modeling.

#### R self-assessment

Finally, please complete this [R Training Assessment](https://cosima.nceas.ucsb.edu/r-self-assessment/) to self-assess your skills in R.

Schedule a session with Julien to debrief on your experience.

---

### HR-related Resources

#### Hours & Kronos

We submit hours online through [Kronos](https://ucsb.kronos.net/wfc/navigator/logonWithUID).  You should recieve an email at the start of your employment adding you to an email listserv that will send reminders on when to submit your timesheet.

We also have a team Google Calendar to manage team events. Julien will add you if you have not been already.

#### UC Path

[UC Path](https://www.ucpath.ucsb.edu/) is the online HR portal and can be accessed with your UCSB Net ID.  It is where you can access things like your paycheck, next date of paycheck, and benefits (if applicable).
