
At NCEAS we are almost exclusively working on collaborative projects where we synthesize existing data to draw larger inferences than any single data set would allow. Because of this, we strongly recommend that each tool used by a team accomplish as many purposes as possible to avoid a project accruing endless "one off" tools that fit a specific purpose but do not accomplish any other tasks. **Streamlining your workflow to just a few broadly useful programs also helps train new team members and ensure that within team protocols are clear and concise to follow.**

The analytical software options available at NCEAS follow directly from this ethos. Although occasionally providing specialty programs (upon request), we have otherwise carefully assembled a powerful lineup of *scripted*, *cross-platform*, *scalable* applications that are *well-supported*, generate *robust results*, and permit *batch processing*. Although these packages require an initial time investment to learn, and may seem intimidating to scientists familiar with only "point-and-click" software, we strongly argue that the long-term payoff is well worth the time investment at the start.

### Collaborative Tools

We strongly recommend that you use **[GitHub](https://github.com/)** both for its capability to visualize *version control* with [`git`](https://pages.github.nceas.ucsb.edu/NCEAS/Computing/git.html) and for its broader value as an integrated project management system.

### Software

**General Analytical Software**

- [R](https://datacarpentry.org/R-genomics/index.html)
    - Note that we strongly suggest using R through [RStudio](https://www.rstudio.com/) as it contains several extremely user-friendly facets that are absent from R's somewhat minimalist base program
- [Python](https://swcarpentry.github.io/python-novice-inflammation/setup.html)

**Spatial Analytical Software**

- [Data Carpentries Geospatial Workshop](https://datacarpentry.org/geospatial-workshop/setup.html)
- [Geographic Resources Analysis Support System (GRASS)](https://pages.github.nceas.ucsb.edu/NCEAS/Computing/grass.html)
- [Quantum GIS (QGIS)](https://pages.github.nceas.ucsb.edu/NCEAS/Computing/quantum_gis.html)
- [PostGIS](https://pages.github.nceas.ucsb.edu/NCEAS/Computing/postgis.html)
- [Geospatial Data Abstraction Library (GDAL / OGR)](https://pages.github.nceas.ucsb.edu/NCEAS/Computing/gdal.html)

**Relational Databases**

- [SQLite](https://swcarpentry.github.io/sql-novice-survey/)

**Code Versioning**

- [`git`](https://swcarpentry.github.io/git-novice/)
    - Again, we strongly recommend using **[GitHub](https://github.com/)** if you use `git` (similarly to R versus RStudio, you *can* use `git` without GitHub but GitHub contains several quality of life improvements and additional functionalities)

**Servers**

- [Unix Shell](https://swcarpentry.github.io/shell-novice/)
    - Note this is also sometimes called the "command line" or--on Macs--"the Terminal"
